### ISSUE TITLE
Include array items in the output of GetAllSchemas

### ISSUE THREAD

**Issue by 2ynn** [pb33f/libopenapi#153]
`GetAllSchemas` does not return index references nested under `items` in an array.

For instance, considering this component:
```
components:
  schemas:
    Array:
      type: array
      items:
        type: skipped
          properties:
            name:
              type: found
```

the paths associated with the index references returned by `GetAllSchemas` are :
- `$.components.schemas.Array`
- `$.components.schemas.Array.items.properties.name`

While we would expect this one to also be included in the output :
- `$.components.schemas.Array.items`

As a result it is not straightforward to perform type checking on the `type: skipped` node.

[Quote from dischord](https://discord.com/channels/923258363540815912/1060173725372264459/1141318397297180793):
> the issue here is that 'items' is not being picked up by the index, is that it literally does not have a key of 'schema', but rather 'items'. Right now, this is expected behavior, based on the code, which is here: https://github.com/pb33f/libopenapi/blob/main/index/extract_refs.go#L43
