### ISSUE TITLE
How to handle AdditionalProperties

### ISSUE THREAD

**Issue by TristanSpeakEasy** [pb33f/libopenapi#29]
Looking into the code AdditionalProperties is an any type which seems to be populated directly from the yaml node.

But it can be either a bool or a schema according to spec.

If its a schema the code currently returns this as a map[string]any I believe, how do I resolve this to the schema type?

**Comment by TristanSpeakEasy** [comment]
So for an object with an AdditionalProperties attribute it can either be defined as:

```yaml
schema:
  type: object
  additionalProperties: true
```

or

```yaml
schema:
  type: object
  additionalProperties:
    type: string
```

here is some code I have trying to handle this, it gets an additionalProperties map but that actually represents a schema

```go
        var additionalProperties map[string]any
	additionalPropertiesAllowed := false
	if g.getOpenAPIVersion() == openAPIVersion31 {
		additionalPropertiesAllowed = true
	}

	apAllowed, ok := schema.AdditionalProperties.(bool)
	if ok {
		additionalPropertiesAllowed = apAllowed
	} else {
		ap, ok := schema.AdditionalProperties.(map[string]any)
		if ok {
			additionalProperties = ap
		}
	}
```

(btw would be great to have a helper function to get the exact type of the document as an enum or similar for handling 3 vs 3.1 differences efficiently)
