### ISSUE TITLE
Bug: Schema renderer incorrectly renders dependent schemas

### ISSUE THREAD

**Issue by geniegeist** [pb33f/libopenapi#409]
Given the schema
```
type: object
properties:
  fishCake:
    type: object
    properties:
      bones:
        type: boolean

dependentSchemas:
  fishCake:
    type: object
    properties:
      cream:
        type: number
        format: double
```
the current implementation renders an example
```
{
  "fishCake": {
    "bones": true,
    "cream": 2.5
  }
}
```
I believe this is incorrect.

Based on [this source](https://json-schema.org/understanding-json-schema/reference/conditionals#dependentSchemas), I expect an example
```
{
  "fishCake": {
    "bones": true
  },
  "cream": 2.5
}
```

## Next steps

There is a unit test `TestRenderExample_Object_DependentSchemas` that tests this. I'll propose a PR in the next days to fix this if you can confirm that this behaviour is indeed incorrect.
